apiVersion: apps/v1
kind: Deployment
metadata:
  name: jibin-echo-app
  namespace: jibin-eks-activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echo-container
        image: hashicorp/http-echo
        args:
          - "-text=Hello, JIBIN!"
        ports:
        - containerPort: 5678
