apiVersion: v1
kind: Service
metadata:
  name: jibin-echo-service
  namespace: jibin-eks-activity
spec:
  selector:
    app: echo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
